before_script: cd hangzhou_viagens-web
language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm install -g
  - npm test
  - npm run build
deploy:
  provider: surge
  skip_cleanup: true
  domain: hangzhou.surge.sh
  project: ./hangzhou_viagens-web/build/
on:
  branch: master
