before_script: cd hangzhou_viagens-web
language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test -g
  - npm run build -g
deploy:
  provider: surge
  skip_cleanup: true
  domain: hangzhou.surge.sh
  project: ./build/
on:
  branch: master
